name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: write
  pull-requests: write
  security-events: write

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          docker --version

      - name: Run SonarScanner (Docker)
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="http://localhost:9000" \
            -e SONAR_LOGIN="${{ secrets.SONAR_TOKEN }}" \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=py-api-demo \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000
